Catkin-ProjectName: rospack
Version: 2.0.6
Depends: catkin, boost, gtest
Description: ROS Package Tool
Author: Brian Gerkey
Maintainer: Brian Gerkey <gerkey@willowgarage.com>
Homepage: http://www.ros.org

Catkin-CopyrightType:  willowgarage
Catkin-DebRulesType: cmake
